version: '3.2'
services:
  webtoon-sketch:
    restart: always
    command: npm start
    container_name: webtoon
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    stdin_open: true